<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */ ?>

<?php if ($block->getSchema()): ?>



    <button id="price-button">
        <span><?= $block->escapeHtml(__('Request Price')) ?></span>
    </button>

    <div id="custom-price-form">
        <form class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-2": {"required":true}}}}'>
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="field-1"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="user-name" id="field-1" title="Field 1" value=""  class="input-text" type="text" data-validate='{"required":true}'/>
                    </div>
                </div>
                <div class="field name required">
                    <label class="label" for="field-2"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="user-email" id="field-2" title="Field 2" value="" class="input-text" type="text" data-validate='{"required":true, "email": true}' />
                    </div>
                </div>
                <div class="comment">
                    <label><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                    <div class="control">
                        <textarea id="user-comment"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="Submit" class="action submit primary" data-role="button-send-form">
                        <span><?= $block->escapeHtml(__('Send Request')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>

<script type="text/x-magento-init">
{"*":{"Houston_Price/js/custom-price-script":{}}}
</script>
<script type="text/x-magento-init">
{"*":{"Houston_Price/js/post-price-ajax":{}}}
</script>





<?php endif; ?>

<?php if (!$block->getSchema()): ?>
   <span class="price-container <?= /* @escapeNotVerified */ $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <?php if ($block->getDisplayLabel()): ?>
        <span class="price-label"><?= /* @escapeNotVerified */ $block->getDisplayLabel() ?></span>
    <?php endif; ?>
    <span <?php if ($block->getPriceId()): ?> id="<?= /* @escapeNotVerified */ $block->getPriceId() ?>"<?php endif;?>
        <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
        data-price-amount="<?= /* @escapeNotVerified */ $block->getDisplayValue() ?>"
        data-price-type="<?= /* @escapeNotVerified */ $block->getPriceType() ?>"
        class="price-wrapper <?= /* @escapeNotVerified */ $block->getPriceWrapperCss() ?>"
    ><?= /* @escapeNotVerified */ $block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()) ?></span>
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    </span>
<?php endif; ?>



